version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: yarolcr
      MONGO_INITDB_ROOT_PASSWORD: V7M7l7e6JyhW